# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799984761af7f241227ff6cd1ecd9386f2045fcc8457146881cf022600bb984d0eece3693608fe4caa7203a53ee20bfe5ae7d8a4d1020db9cfb1d899d9820029

test:
  secret_key_base: e999d1a25c704a1c573580fffad4788176814b38cd20de8f6bb3026b4e9f9533a2c9611d75e7f2cb36a73ad48d9cadad4f10d2d62202621bdee86fc2f5277576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
